version: 2.1
jobs:
  build_docker:
    docker:
      - image: docker
    environment:
      REGISTRY_ENDPOINT: registry.hub.docker.com
      REGISTRY_REPO: harmeetg/fluttermovie
    steps:

      # checkout the repository
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: false

      # build and push Docker image
      - run: |
          docker login ${REGISTRY_ENDPOINT} --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
          docker build --rm=true --pull=true -t ${REGISTRY_ENDPOINT}/${REGISTRY_REPO} -f Dockerfile.web ./
          TAG=${CIRCLE_SHA1:0:7} && docker tag ${REGISTRY_ENDPOINT}/${REGISTRY_REPO} ${REGISTRY_ENDPOINT}/${REGISTRY_REPO}:${TAG} && docker push ${REGISTRY_ENDPOINT}/${REGISTRY_REPO}:${TAG}
          TAG=${CIRCLE_SHA1} && docker tag ${REGISTRY_ENDPOINT}/${REGISTRY_REPO} ${REGISTRY_ENDPOINT}/${REGISTRY_REPO}:${TAG} && docker push ${REGISTRY_ENDPOINT}/${REGISTRY_REPO}:${TAG}
          TAG=circleci && docker tag ${REGISTRY_ENDPOINT}/${REGISTRY_REPO} ${REGISTRY_ENDPOINT}/${REGISTRY_REPO}:${TAG} && docker push ${REGISTRY_ENDPOINT}/${REGISTRY_REPO}:${TAG}

workflows:
  version: 2.1
  hugo_and_docker:
    jobs:
      - build_docker:
          context: demo
