default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure that your git status is not dirty
	ensure_git_status_clean

	# Increment the build number (not the version number)
	# Providing the xcodeproj is optional
	increment_build_number

	match(type: "appstore", readonly: is_ci)

	build_app(
		workspace: "Runner.xcworkspace",
		scheme: "Runner",
		export_method: "app-store",
		export_options: {
			provisioningProfiles: {
				"com.webkrux.inkino" => "match AppStore com.webkrux.inkino"
			}
		}
	)

    upload_to_testflight

	# Commit the version bump
	commit_version_bump

	# Add a git tag for this build. This will automatically
	# use an appropriate git tag name
	add_git_tag

	# Push the new commit and tag back to your git remote
	push_to_git_remote

  end
end
