name: Publish IOS app

on:
  push:
    branches: [ ios ]

jobs:

  build_ios:
    if: |
      !contains(github.event.head_commit.message, 'ci skip')
      && !contains(github.event.pull_request.title, 'ci skip')
    runs-on: macos-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: build
      timeout-minutes: 1
      run: bash _ops/build.ios.sh

    - name: install
      run: bash _ops/publish_pre.ios.sh

    - name: publish
      timeout-minutes: 15
      run: bash _ops/publish.ios.sh
      env:
        PA_TOKEN: ${{ secrets.PA_TOKEN }}
        TMDB_KEY: ${{ secrets.TMDB_KEY }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}

