name: rebase-command
on:
  repository_dispatch:
    types: [rebase-command]
jobs:
  rebase:
    if: github.event.client_payload.pull_request.rebaseable == true
    runs-on: ubuntu-latest
    steps:
     - name: Checkout pull request
       uses: actions/checkout@v2
       with:
         token: ${{ secrets.PA_TOKEN }}
         repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
         ref: ${{ github.event.client_payload.pull_request.head.ref }}
         fetch-depth: 0

     - name: Rebase
       run: |
         git config --global user.name 'gitops-bot'
         git config --global user.email '52609384+gitops-bot@users.noreply.github.com'
         git remote add base https://x-access-token:${{ secrets.PA_TOKEN }}@github.com/${{ github.event.client_payload.pull_request.base.repo.full_name }}.git
         git fetch base ${{ github.event.client_payload.pull_request.base.ref }}
         git rebase base/${{ github.event.client_payload.pull_request.base.ref }}
         git push --force-with-lease

     - name: Update comment
       uses: peter-evans/create-or-update-comment@41f3207a84f33bd70388036109082784d059dcaa
       with:
         token: ${{ secrets.PA_TOKEN }}
         repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
         comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
         body: |
           >Pull request successfully rebased
         reactions: hooray

  notRebaseable:
    if: github.event.client_payload.pull_request.rebaseable != true
    runs-on: ubuntu-latest
    steps:
     - name: Update comment
       uses: peter-evans/create-or-update-comment@41f3207a84f33bd70388036109082784d059dcaa
       with:
         token: ${{ secrets.PA_TOKEN }}
         repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
         comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
         body: |
           >Pull request is not rebaseable
         reactions: hooray

